def drep_to_table(drep_dir, output, suffix=".fna"):
    """
    This function accepts an output directory generated by dRep
    https://drep.readthedocs.io/en/latest/index.html
    
    It converts the outputs into a three column CSV table of
    genome, cluster, representative
    
    And also removes the file extension specified by suffix
    """
    # Genomes and cluster designations
    cdb_df = pd.read_csv(drep_dir + '/data_tables/Cdb.csv')
    cdb_df.genome = cdb_df.genome.str.replace(suffix, "")

    # Winning genomes
    wdb_df = pd.read_csv(drep_dir + '/data_tables/Wdb.csv')
    wdb_df.genome = wdb_df.genome.str.replace(suffix, "")

    #Merge the two tables, keeping only the three columns we want
    df1 = (pd.merge(cdb_df, 
                    wdb_df, 
                    how = 'left', 
                    left_on = 'secondary_cluster', 
                    right_on = 'cluster')
           .rename(columns = {"genome_y" : "representative",
                             "genome_x" : "contig"}, 
                   copy = False)
           .loc[:,['contig',
                   'cluster',
                   'representative'
                  ]
               ]
          )
    
    #Add a column for the size of the cluster
    df1["cluster_size"] = df1.groupby('cluster')['contig'].transform('count')

    df1.to_csv(output, index = False)